import os
import json
import pandas as pd
import numpy as np
import uuid
import datetime

def main():
    # Setup directories
    base_dir = os.path.dirname(os.path.abspath(__file__))
    mocks_dir = os.path.join(base_dir, "mocks")
    group_a_dir = os.path.join(mocks_dir, "group_A_data")
    group_b_dir = os.path.join(mocks_dir, "group_B_data")
    group_c_dir = os.path.join(mocks_dir, "group_C_data")
    
    os.makedirs(group_a_dir, exist_ok=True)
    os.makedirs(group_b_dir, exist_ok=True)
    os.makedirs(group_c_dir, exist_ok=True)
    
    np.random.seed(42)
    regions = ["Seoul", "Busan", "Daegu", "Incheon", "Gwangju", "Daejeon", "Ulsan", "Sejong", "Gyeonggi", "Gangwon", "Chungbuk", "Chungnam", "Jeonbuk", "Jeonnam", "Gyeongbuk", "Gyeongnam", "Jeju"]
    product_families = ["mobile_launch", "bulky_appliance", "finished_goods", "secure_node"]
    
    print("Generating Group A (Demand & Data) Mocks...")
    # Group A: Demand and OD
    demand_data = [{"region": r, "demand_tons": round(np.random.uniform(500, 5000), 2)} for r in regions]
    pd.DataFrame(demand_data).to_csv(os.path.join(group_a_dir, "regional_demand.csv"), index=False)
    
    od_data = []
    for o in regions:
        for d in regions:
            if o != d:
                od_data.append({"origin": o, "destination": d, "flow_tons": round(np.random.uniform(50, 1000), 2)})
    pd.DataFrame(od_data).to_csv(os.path.join(group_a_dir, "od_matrix_17_region.csv"), index=False)
    
    print("Generating Group B (Cost & Optimization) Mocks...")
    # Group B: Cost and Scenarios
    hubs = ["GG_METRO", "BS_PORT", "DJ_CENTRAL", "IC_AIRPORT", "GW_BULKY"]
    cost_data = []
    for h in hubs:
        cost_data.append({"hub_id": h, "fixed_cost": round(np.random.uniform(10000, 50000), 2), "capacity": round(np.random.uniform(5000, 20000), 2)})
    pd.DataFrame(cost_data).to_csv(os.path.join(group_b_dir, "warehouse_fixed_cost_by_hub.csv"), index=False)
    
    scenarios = []
    for i in range(6):
        scenarios.append({
            "id": f"S{i}", "label": f"Scenario {i}", 
            "cost_index": 100 if i == 0 else round(np.random.uniform(80, 120), 1),
            "service_level": round(np.random.uniform(0.7, 0.99), 2),
            "risk_score": round(np.random.uniform(0.1, 0.5), 2),
            "opened_hubs": np.random.choice(hubs, size=np.random.randint(2, 5), replace=False).tolist()
        })
    pd.DataFrame([{"id": s["id"], "cost_index": s["cost_index"], "service": s["service_level"]} for s in scenarios]).to_csv(os.path.join(group_b_dir, "scenario_comparison.csv"), index=False)
    
    print("Generating Group C (Diagnosis & Synthesis) Mocks...")
    # Group C: JSONs for rules and playbook
    rules = {"rules": [{"region": "Seoul", "family": "mobile_launch", "confidence": 0.9}]}
    with open(os.path.join(group_c_dir, "classifier_rules.json"), "w") as f:
        json.dump(rules, f, indent=2)
        
    playbook = [{"event": "Q1_Galaxy_Launch", "actions": ["Pre-position inventory", "Reserve extra line-haul"]}]
    with open(os.path.join(group_c_dir, "seasonal_playbook.json"), "w") as f:
        json.dump(playbook, f, indent=2)
        
    print("Generating Final Engine Master JSON...")
    # Comprehensive Master JSON
    master_json = {
        "run_info": {
            "scenario_run_id": str(uuid.uuid4()),
            "engine_version": "v2.0-proxy",
            "execution_time_ms": 12450.5,
            "timestamp": datetime.datetime.now().isoformat()
        },
        "proxy_scope": {
            "is_proxy": True,
            "data_source": "Korean Freight O/D 2023 + Registry",
            "disclaimer": "This analysis is generated by LogiHub Proxy Engine using public proxy data."
        },
        "input_data_summary": {
            "total_rows_ingested": 140530955,
            "total_tons_processed": sum(d["demand_tons"] for d in demand_data),
            "date_range": "2023-01-01 to 2023-12-31"
        },
        "master_data": {
            "total_regions": 17,
            "total_warehouses": 5900,
            "product_families": product_families
        },
        "demand": {
            "total_demand_tons": sum(d["demand_tons"] for d in demand_data),
            "top_origin": "Gyeonggi",
            "top_destination": "Seoul"
        },
        "product_segmentation": {
            "rules_applied": 7,
            "distribution": {"mobile_launch": 0.2, "bulky_appliance": 0.3, "finished_goods": 0.4, "secure_node": 0.1}
        },
        "baseline_network": {
            "opened_hubs": ["GG_METRO", "BS_PORT", "DJ_CENTRAL"],
            "total_cost": 4500000.0
        },
        "capacity_model": {
            "total_network_capacity": 85000.0,
            "utilization_rate": 0.88
        },
        "diagnosis": {
            "overloaded_hubs": ["GG_METRO"],
            "high_cost_lanes": ["Gyeonggi -> Busan"]
        },
        "optimization_models": {
            "solvers_used": ["CBC", "P-Median", "Hybrid-CFLP"],
            "scenarios": scenarios
        },
        "recommended_network": {
            "recommended_scenario": "S3",
            "hubs": [
                {"hub_id": "GG_METRO", "role": "metro_fulfillment", "status": "watchlist"},
                {"hub_id": "BS_PORT", "role": "southern_port", "status": "healthy"}
            ]
        },
        "allocation": [
            {"region": "Seoul", "hub_id": "GG_METRO", "product": "mobile_launch"}
        ],
        "warnings": ["Imputed missing product_family for 1.2% of shipments."],
        "errors": [],
        "artifacts": [
            "mocks/group_A_data/regional_demand.csv",
            "mocks/group_B_data/scenario_comparison.csv",
            "mocks/group_C_data/classifier_rules.json"
        ],
        "outcome_report": {
            "markdown_path": "output/outcome_sample_full.md",
            "roadmap": [{"phase": 1, "timeline_months": "0-2", "actions": ["Reallocate north"]}],
            "business_case": {
                "cost_saving_pct": 15.4,
                "executive_summary": "By migrating to S3, we achieve a 15% cost reduction."
            }
        }
    }
    
    final_json_path = os.path.join(mocks_dir, "mock_engine_output_final.json")
    with open(final_json_path, "w") as f:
        json.dump(master_json, f, indent=2)
        
    print(f"Success! Generated all intermediate packages and master JSON at {mocks_dir}")

if __name__ == "__main__":
    main()
